version: '3.8'
services:
  web:
    container_name: angular-app-container
    build:
      context: .    # Esto apunta a la raíz del directorio del proyecto
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    restart: unless-stopped